# Generated by Django 5.1.5 on 2025-02-09 15:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_cookie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cookie')),
            ],
        ),
    ]
